### ISSUE TITLE
Adhere to $VIRTUAL_ENV

### ISSUE THREAD

**Issue by Bengt** [syphar/restore-virtualenv#156]
Hi!

I have all my virtual environments under `venv`, not `.venv`. So, I would like to configure this action to adhere to my convention.

Since restore-virtualenv already sets the `$VIRTUAL_ENV` environment variable, why not adhere to it, too? I could configure it like so:

```yaml
      - name: Set VIRTUAL_ENV (Ubuntu | macOS)
        if: startsWith( matrix.os, 'ubuntu-' ) ||
            startsWith( matrix.os, 'macos-' )
        run: export VIRTUAL_ENV=venv

      - name: Set VIRTUAL_ENV (Windows)
        if: startsWith( matrix.os, 'windows-' )
        run: setx VIRTUAL_ENV venv
```

Alternatively, one could also introduce a `with` parameter to the action like so:

```yaml
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          virtual_env: venv
```
