### ISSUE TITLE
Virtual-env name parameter

### ISSUE THREAD

**Issue by damian-t** [syphar/restore-virtualenv#213]
I am running `n` python projects with potentially conflicting dependencies. Preferably I'd like to use your action to create `n` virtual-envs on each runner, linked to `n` caches.

As I understand it, I can use **custom_cache_key_element** to create the `n` caches,
```
 - uses: syphar/restore-virtualenv@v1.1
   id: cache-virtualenv
   with:
    custom_cache_key_element: project_i
```
but they all seem to refer to the same virtualenv:

`home/runner/.virtualenvs/.venv/`

Is this the expected behaviour?
