### ISSUE TITLE
Support setup.py

### ISSUE THREAD

**Issue by heynemann** [syphar/restore-virtualenv#354]
I would love to use this action but my projects do not include a requirements.txt file. Only what's described in setup.py. Maybe there's a way to support setup.py as a fallback?

**Comment by syphar** [comment]
@heynemann you can use the `requirement_files` setting in the action to provide the file to be checked for changes. 

```
- uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: setup.cfg
```
