### ISSUE TITLE
pip failing in virtualenv for python 3.10

### ISSUE THREAD

**Issue by GitHubPyTest** [syphar/restore-virtualenv#355]
Quick run showing the issue:

https://github.com/AndrewOfC/githubpy/runs/4943345353?check_suite_focus=true

pip failing for python 3.10 but not for python 3.9 or 3.6

```yaml
name: Virtual Env Setup Issue
on: [ push ]

jobs:
  Ubuntu_py3-6:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - uses: syphar/restore-virtualenv@v1
      - name: Run
        run: |
          pip install requests
          python -c "print('hello world')"

  Ubuntu_py3-9:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: syphar/restore-virtualenv@v1
      - name: Run
        run: |
          pip install requests
          python -c "print('hello world')"

  Ubuntu_py3-10:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: syphar/restore-virtualenv@v1
      - name: Run
        run: |
          pip install requests
          python -c "print('hello world')"

```

**Comment by syphar** [comment]
Thank you for the report! 

I added python 3.10 to my E2E test matrix (https://github.com/syphar/restore-virtualenv/pull/356) and it seems to pass without issues. 

To me it looks like the cached virtualenv is somehow broken. Since the cache is not by job or workflow, but just by the python version and dependencies this flow would reuse an existing cache from another flow. 

Can you add some `custom_cache_key_element` to see if that helps? Then the cache is fresh. 

it would look like this: 
```yaml 
- uses: syphar/restore-virtualenv@v1
  id: cache-virtualenv
  with:
    custom_cache_key_element: some_new_name
```
